apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: istio-system
data:
  config.yaml: |
    domain: ticket-system
    descriptors:
      - key: generic_key
        value: all
        rate_limit:
          unit: second
          requests_per_unit: 5