apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booking-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AleksandrErmolaev/cinema-tickets.git
    targetRevision: main
    path: helm-charts/booking-service
  destination:
    server: https://kubernetes.default.svc
    namespace: booking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true