apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "movie-service.fullname" . }}-config
  labels:
    {{- include "movie-service.labels" . | nindent 4 }}
data:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
  